// This file is generated by Slice Machine. Update with care!

import LinkCards from './LinkCards';
import Text from './Text';

export {
	LinkCards,
	Text,
};

export const components = {
	link_cards: LinkCards,
	text: Text,
};
